spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdpay
    username: root
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
